config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { :registrations => 'users/registrations' }
  resources :books
  resources :notes
  root :to => 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :note, dependent: :delete_all
  belongs_to :user
  
  validates :name, null:false 
  validates_uniqueness_of :name, scope: :user_id
  validates_length_of :name, maximum: 50, message: "the name of the book must have a maximum of 30 characters"

  scope :books_per_user, -> (user_id){ where("user_id == ?",user_id )} 
  
  def empty
  	Note.empty(self.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.books_per_user(current_user.id)
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @notes = Note.notes_per_book(@book.id)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    if @book.name != "Global"
      respond_to do |format|
        if @book.update(book_params)
          format.html { redirect_to @book, notice: 'Book was successfully updated.' }
          format.json { render :show, status: :ok, location: @book }
        else
          format.html { render :edit }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to books_url, alert: "Can't edit Global book" }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    if @book.name != "Global"
      @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      @book.empty
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Book was successfully empty.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
      if(@book.user_id != current_user.id)
        render :'errors/403', status: :forbidden, :layout => false
      end
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :note_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
<% if book.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

  <ul>
    <% book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-group">
  <div class="field">
    <%= form.label :name%>
    <%= form.text_field :name, class: "form-control" ,  autocomplete: 'off', :required => 'required'%>
  </div>
</div>
<div class="actions">
  <%= form.submit  class: "btn btn-primary" %>
</div>
<% end %>

app/views/books/edit.html.erb
<div class="d-flex justify-content-center align-items-center container mt-5">
	<div class="row p-4 text-light bg-dark">
		<div class="col-sm-10 offset-sm-1">
			<h1 class="my-4">Editing Book</h1>

			<%= render 'form', book: @book %>

			<%= link_to 'Show', @book %> |
			<%= link_to 'Back', :back %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="d-flex justify-content-center"> My books</h1>
<div class="container-fluid">
  <% @books.in_groups_of(4,false).each do |book_group| %>
  <div class="row">
    <% book_group.each do |book| %>
    <div class="col-6 col-sm-4 col-xl-3  my-4">
      <div class="card mw-25">
        <div class="card-body">
          <h4 class="card-title d-flex justify-content-center"><%= book.name %></h4>
          <hr>
          <ul class="list-group">
            <li class="list-group-item"><%= link_to_if book.name != "Global", 'Edit', edit_book_path(book) %> </li>
            <% if book.name == "Global"%>
              <li class="list-group-item"><%= link_to 'Empty', book, method: :delete, data: { confirm: 'Empty book?' } %></li>
            <% else %>
             <li class="list-group-item"><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Delete book?' } %></li>
            <% end %>
            <li class="list-group-item"><%= link_to 'Show', book %></li>
          </ul>
        </div>
        <div class="card-footer">
          <small class="text-muted">Created at: <%= book.created_at.strftime("%d/%m/%Y") %> </small>
        </div>
      </div>
    </div>
    <% end %>
    <hr>
  </div>
  <% end %>
</div>
<style type="text/css">
  a.books{
    color:#966b3a!important;
  }
</style>

app/views/books/new.html.erb
<div class="d-flex justify-content-center align-items-center container mt-5">
	<div class="row p-4 text-light bg-dark">
		<div class="col-sm-10 offset-sm-1">
			<h1 class="my-4">New Book</h1>

			<%= render 'form', book: @book %>

			<%= link_to 'Back', :back %>
		</div>
	</div>
</div>
<style type="text/css">
  a.create_book{
    color:#966b3a!important;
  }
</style>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="d-flex justify-content-center"> <%= @book.name %> </h1>
<div class="container-fluid">
  <% @notes.in_groups_of(3,false).each do |notes_group| %>
  <div class="row">
    <% notes_group.each do |note| %>
    <div class="col-6 col-sm-4 col-xl-4  my-4">
      <div class="card mw-25">
        <div class="card-body">
          <h4 class="card-title d-flex justify-content-center"><%= note.name %></h4>
          <hr>
          <ul class="list-group ">
            <li class="list-group-item content">
              <%= sanitize format(note.content) %>
            </li>
            <ul class=" list-group list-group-horizontal d-flex text-center">
              <li class="list-group-item flex-fill"><%= link_to 'Edit', edit_note_path(note) %> </li>
              <li class="list-group-item flex-fill"><%= link_to 'Delete', note, method: :delete, data: { confirm: 'Delete note?' } %></li>
              <li class="list-group-item flex-fill"><%= link_to 'Show', note %></li>
            </ul>
          </ul>
        </div>
        <div class="card-footer">
          <small class="text-muted">Created at: <%= note.created_at.strftime("%d/%m/%Y") %> </small>
        </div>
      </div>
    </div>
    <% end %>
    <hr>
  </div>
  <% end %>
</div>
<style>
  .content{
    height: 15rem; 
    overflow: auto;
    white-space:break-word; /* Don't forget this one */
    text-overflow: ellipsis;
  }
  a.books{
    color:#966b3a!important;
  }
  </style>